#!/usr/bin/zsh

PACKAGES=(
   bc busybox clang coreutils
   curl diffutils dx ecj make
   man nodejs python python2
   ruby termux-am termux-api
   termux-exec termux-tools
   tmux util-linux vifm vim-python
   wget zip zsh
)

EXTRA_PACKAGES=(
   cmatrix ctags figlet
   fish htop sqlite
   toilet tree xz-utils
)
OLD_DIRECTORY=$(pwd)
# directory where setup scripts are generated
SCRIPTS_DIRECTORY=$(realpath ${0:h})/setup-scripts

DOWNLOAD_SCRIPT_NAME=download.zsh
EXTRAS_SCRIPT_NAME=extras.zsh
SYMLINK_SCRIPT_NAME=symlink.zsh

SYMLINK_TARGET_FILE=symlink.targets
SYMLINK_DESTINATION=$HOME/hello

if [ ! -d $SCRIPTS_DIRECTORY ]; then
   mkdir $SCRIPTS_DIRECTORY
   print -P directory $(EM $SCRIPTS_DIRECTORY) was created.
fi
cd $SCRIPTS_DIRECTORY

if [ ! -d $SYMLINK_DESTINATION ]; then
   mkdir $SYMLINK_DESTINATION
   print -P directory $(EM $SYMLINK_DESTINATION) was created.
fi

IFS_SAVE=$IFS

EM() {
   echo %F{105}%B$1%b%f
}
write() {
   echo ${argv:2} >> $1 
}

init-shebang() {
   echo '#!/usr/bin/zsh' > $1
}

apt-packages() {
   output_filename=$1 && shift 1 argv
   init-shebang $output_filename

   write $output_filename apt update '&& apt upgrade'
   write $output_filename apt install $@

   print -P ${(r:30::.:)$(EM $output_filename)}generated !
}

symlink-files() {
   init-shebang $1

   if [ ! -f ../$SYMLINK_TARGET_FILE ]; then
      print -P $(EM $SYMLINK_TARGET_FILE) does not exist !
   fi
   IFS="
"
   for target in $(cat ../$SYMLINK_TARGET_FILE); do
      if [[ ${target:0:2} = '--' ]]; then
         LINK_TYPE=${target:2:-2}
         continue
      fi

      # the sed substitution is for handling multiple files
      # on one line in the 'symlink.targets' file
      for file in $(echo $target | sed "s/ /\n/g"); do
         write $1 "if [ ! -f $SYMLINK_DESTINATION/$file ] || [ ! -d $SYMLINK_DESTINATION/$file ]; then"

         if [[ $LINK_TYPE = "HARD" ]]; then
            write $1 "   ln -P ../$file $SYMLINK_DESTINATION\nfi"
            continue
         fi
         write $1 "   ln -s ../$file $SYMLINK_DESTINATION\nfi"
      done
   done
   print -P ${(r:30::.:)$(EM $SYMLINK_SCRIPT_NAME)}generated !
   IFS=$IFS_SAVE
}
run-setup-scripts() {
   for file in $SCRIPTS_DIRECTORY/*; do
      source $file
      echo $file
   done
}

main() {
   apt-packages ${DOWNLOAD_SCRIPT_NAME} ${PACKAGES}
   apt-packages ${EXTRAS_SCRIPT_NAME} ${EXTRA_PACKAGES}

   write ${EXTRAS_SCRIPT_NAME} gem install lolcat
   write ${EXTRAS_SCRIPT_NAME} git clone http://github.com/steampunk08/vim-steampunklights ~/vim-steampunklights

   symlink-files ${SYMLINK_SCRIPT_NAME}

   run-setup-scripts
   print "remember to run :PluginInstall! in vim"
   cd ${OLD_DIRECTORY}
}

main
