#!/bin/bash

D=setup-scripts
# WARNING: 
#   this script depends on all the scripts
#   under the "setups/" directory

# load utility functions
source $D/utils.bash

clear
echo_normal "Starting Setup Script"

SCRIPT_NAME=$(basename $0)
SCRIPT_PATH=$(realpath ${0%${SCRIPT_NAME}})

# TARGETS_FILE=$SCRIPT_PATH/setups/symlink.targets

TARGETS_FILE=$SCRIPT_PATH/symlink.targets

if [[ -z $DESTINATION ]]; then
   # DESTINATION=$HOME/safe
   read -p "Where do you want to setup? " DESTINATION
fi
DESTINATION=$(eval echo $DESTINATION)

if [[ -z $DEVICE_TYPE ]]; then
   # DEVICE_TYPE=android
   read -p "Which do you use (android|desktop)? " DEVICE_TYPE
fi

if [[ ! -d $D ]]; then
   alias echo_="COLOR_NORMAL=196 echo_normal"
   echo_ "This script must be in the same directory as the"
   echo_ "setupscripts/ directory."
   exit 1
fi

if [ ! -d $DESTINATION ]; then
   mkdir -pv $DESTINATION
fi

echo_progress "Creating links..."
DEVICE=$DEVICE_TYPE SOURCE_PATH=$SCRIPT_PATH $D/lntargs $TARGETS_FILE $DESTINATION
